---
title: "Test Code"
author: "Gustavo T ALckmin"
date: "16/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Code Example for 

This example code was developed for an mock-up presentation. The topic of it is the use of statistical learning for spectral data.


```{r libraries, message=F, echo=F}
# devtools::install_gitlab('jbferet/prospect')
library(prospect) # library by Jean-Baptiste Feret
library(dplyr)
library(ggplot2)
library(ggpubr)
library(tidymodels)
library(rsample)
library(hyperSpec)
```

```{r}
set.seed(1987)
number_spectra<-500

CHL <- 100*runif(number_spectra) #Chlorophyll
CAR <- 25*runif(number_spectra) #caroteinods
ANT <- 2*runif(number_spectra) # Anto
EWT <- 0.04*runif(number_spectra)
LMA <- 0.02*runif(number_spectra)
N   <- 1+2*runif(number_spectra)
Input_PROSPECT <- data.frame('CHL'=CHL,'CAR'=CAR,'ANT'=ANT,'EWT'=EWT,'LMA'=LMA,'N'=N)
LUT <- prospect::PROSPECT_LUT(SpecPROSPECT,Input_PROSPECT)
wavelength.vector<- 400:2500
        

hyperSpec.obj<-  new("hyperSpec", spc = t(LUT$Reflectance), wavelength = wavelength.vector, data = LUT$Input_PROSPECT)

#hyperSpec::plotspc(object=hyperSpec.obj[,,])     # Base Plot
hyperSpec::qplotspc(x = hyperSpec.obj) + 
        aes(colour= CHL) + 
        theme_minimal() # ggplot2

```


```{r}
# Applying different preprocessing techniques
detrend.spc<- prospectr::detrend(X = hyperSpec.obj$spc, wav = wavelength.vector)
snv.spc<- prospectr::standardNormalVariate(X = hyperSpec.obj$spc)
gapDer.spc<- prospectr::gapDer(X= hyperSpec.obj$spc, m = 2, w = 11)
msc.spc<- prospectr::msc(X = hyperSpec.obj$spc)


#creating HyperSpec Objects

hyperSpec.detrend<-  new("hyperSpec", spc = detrend.spc, wavelength = wavelength.vector, data = LUT$Input_PROSPECT)
hyperSpec.SNV<-  new("hyperSpec", spc = snv.spc, wavelength = wavelength.vector, data = LUT$Input_PROSPECT)
hyperSpec.gapDer<- new("hyperSpec", spc = gapDer.spc, wavelength = wavelength.vector[11:2087], data = LUT$Input_PROSPECT)
hyperSpec.msc<- new("hyperSpec", spc = msc.spc, wavelength = wavelength.vector, data = LUT$Input_PROSPECT)
#Plotting effects


ggdetrend<- hyperSpec::qplotspc(x = hyperSpec.detrend) + 
        aes(colour= CHL) + 
        theme_minimal() # ggplot2

ggSNV<- hyperSpec::qplotspc(x = hyperSpec.SNV) +
        aes(colour= CHL) + 
        theme_minimal() # ggplot2

ggGapDer<- hyperSpec::qplotspc(x = hyperSpec.gapDer) +
        aes(colour= CHL) + 
        theme_minimal() # ggplot2

ggMsc<- hyperSpec::qplotspc(x = hyperSpec.msc) +
        aes(colour= CHL) + 
        theme_minimal()




ggpubr::ggarrange(ggdetrend, ggSNV, ggGapDer, ggMsc, common.legend = T)

```



```{r}
data<- as.data.frame(cbind(hyperSpec.detrend@data$CHL, 
                           #hyperSpec.detrend@data$PROT, 
                           hyperSpec.detrend@data$LMA ,  hyperSpec.detrend@data$spc))
colnames(data)<- c("CHL",#"PROT", 
                   "LMA", hyperSpec.detrend@data$spc %>% colnames())

norm_rec <- 
  recipe(CHL + 
                 #PROT +
                 LMA ~ ., data = data) 

set.seed(57343)
folds <- vfold_cv(data = data, repeats = 2, v=5)

folds <- 
  folds %>%
  dplyr::mutate(recipes = map(splits, prepper, recipe = norm_rec))

```



```{r}
library(pls)

get_var_explained <- function(recipe, ...) {
  
  # Extract the predictors and outcomes into their own matrices
  y_mat <- bake(recipe, new_data = NULL, composition = "matrix", all_outcomes())
  x_mat <- bake(recipe, new_data = NULL, composition = "matrix", all_predictors())
  
  # The pls package prefers the data in a data frame where the outcome
  # and predictors are in _matrices_. To make sure this is formatted
  # properly, use the `I()` function to inhibit `data.frame()` from making
  # all the individual columns. `pls_format` should have two columns.
  pls_format <- data.frame(
    endpoints = I(y_mat),
    measurements = I(x_mat)
  )
  # Fit the model
  mod <- plsr(endpoints ~ measurements, data = pls_format)
  
  # Get the proportion of the predictor variance that is explained
  # by the model for different number of components. 
  xve <- explvar(mod)/100 

  # To do the same for the outcome, it is more complex. This code 
  # was extracted from pls:::summary.mvr. 
  explained <- 
    drop(pls::R2(mod, estimate = "train", intercept = FALSE)$val) %>% 
    # transpose so that components are in rows
    t() %>% 
    as_tibble() %>%
    # Add the predictor proportions
    mutate(predictors = cumsum(xve) %>% as.vector(),
           components = seq_along(xve)) %>%
    # Put into a tidy format that is tall
    pivot_longer(
      cols = c(-components),
      names_to = "source",
      values_to = "proportion"
    )
}
```



```{r}
folds <- 
  folds %>%
  mutate(var = map(recipes, get_var_explained),
         var = unname(var))
```



```{r}
variance_data <- 
  bind_rows(folds[["var"]]) %>%
  filter(components <= 15) %>%
  group_by(components, source) %>%
  summarize(proportion = mean(proportion))
```


```{r}
detrend_varexp<- ggplot(variance_data, aes(x = components, y = proportion, col = source)) + 
  geom_line() + 
  geom_point() 
```

```{r}

data_gap<-  as.data.frame(cbind(hyperSpec.detrend@data$CHL, 
                           #hyperSpec.detrend@data$PROT, 
                           hyperSpec.detrend@data$LMA ,  hyperSpec.gapDer@data$spc))
folds_gap <- vfold_cv(data = data_gap, repeats = 2, v=5)

folds_gap <- 
  folds %>%
  dplyr::mutate(recipes = map(splits, prepper, recipe = norm_rec))

folds_gap <- 
  folds_gap %>%
  mutate(var = map(recipes, get_var_explained),
         var = unname(var))

```



```{r}
variance_data_gap <- 
  bind_rows(folds_gap[["var"]]) %>%
  filter(components <= 15) %>%
  group_by(components, source) %>%
  summarize(proportion = mean(proportion))

gap_varexp<- ggplot(variance_data_gap, aes(x = components, y = proportion, col = source)) + 
  geom_line() + 
  geom_point() 
```


```{r}
ggpubr::ggarrange(gap_varexp, detrend_varexp, common.legend = T)
```

